version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: 'us-west-2"
	  IMAGE_REPO_NAME: "docker_demo"
	  IMAGE_TAG: "latest"
	  AWS_ACCOUNT_ID: "337226440425"
	
phases:
  install:
    commands:
      - echo Entered the install phase…
	    – apt-get update -y
	    – apt-get install -y software-properties-common
      – add-apt-repository ppa:openjdk-r/ppa
      – apt-get update -y
      – apt-get install -y openjdk-8-jdk
      – apt-get install -y maven
  pre_build:
    commands:
      – echo Logging in to Amazon ECR…
      – $(aws ecr get-login –no-include-email –region $AWS_DEFAULT_REGION)
  build:
    commands:
      – mvn clean
      – mvn install
      – echo Building the Docker image…
      – docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      – docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"docker_demo","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
  post_build:
    commands:
	  - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
artifacts:
    files:
	  - target/Spring-Boot-Hello-App-0.0.1-SNAPSHOT.war
	  - imagedefinitions.json
